# Unicast Discovery (disable multicast)
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["127.0.0.1"]

cluster:
  name: NATL2236LJCOX

  network:
    host: 127.0.0.1

    path:
      logs: /usr/local/var/log
      data: /usr/local/var/data
