# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 21:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mysql_type', models.CharField(choices=[('varchar', 'VARCHAR'), ('char', 'CHAR'), ('text', 'TEXT'), ('longtext', 'LONGTEXT'), ('decimal', 'DECIMAL'), ('double', 'DOUBLE'), ('int', 'INT'), ('date', 'DATE'), ('datetime', 'DATETIME'), ('timestamp', 'TIMESTAMP'), ('json', 'JSON'), ('binary', 'BINARY')], max_length=300)),
                ('information_type', models.CharField(blank=True, choices=[('full_name', 'Full Name'), ('last_name', 'Last Name'), ('first name', 'First Name'), ('middle_name', 'Middle Name'), ('other_name', 'Other Name'), ('full_address', 'Full Address'), ('street', 'Street'), ('city', 'City'), ('county', 'County'), ('state', 'State'), ('zip', 'ZIP'), ('other_add', 'Other Address'), ('organization_name', 'Organization Name')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_type', models.CharField(choices=[('pio', 'Press Officer'), ('tech', 'Technical Contact'), ('leg', 'Legal Contact'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.CharField(max_length=300)),
                ('table', models.CharField(max_length=300)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('upload_log', models.TextField(blank=True)),
                ('source', models.CharField(max_length=300)),
                ('next_update', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contacts',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Table'),
        ),
        migrations.AddField(
            model_name='column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.Table'),
        ),
    ]
