# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_length',
            field=models.IntegerField(null=True),
        ),
    ]
