# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_column_column_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='column_length',
        ),
        migrations.AddField(
            model_name='column',
            name='column_size',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='information_type',
            field=models.CharField(blank=True, choices=[('full_name', 'Full Name'), ('last_name', 'Last Name'), ('first name', 'First Name'), ('middle_name', 'Middle Name'), ('other_name', 'Other Name'), ('full_address', 'Full Address'), ('street', 'Street'), ('city', 'City'), ('county', 'County'), ('state', 'State'), ('zip', 'ZIP'), ('other_add', 'Other Address'), ('organization_name', 'Organization Name'), ('corp_or_person', 'Corporate or Person Name')], max_length=30, null=True),
        ),
    ]
