# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20161018_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='column',
        ),
        migrations.AlterField(
            model_name='column',
            name='information_type',
            field=models.CharField(blank=True, choices=[('full_name', 'Full Name'), ('last_name', 'Last Name'), ('first name', 'First Name'), ('middle_name', 'Middle Name'), ('other_name', 'Other Name'), ('full_add', 'Full Address'), ('street_add', 'Street'), ('city_add', 'City'), ('county_add', 'County'), ('state_add', 'State'), ('zip_add', 'ZIP'), ('other_add', 'Other Address'), ('organization_name', 'Organization Name'), ('corp_or_person_name', 'Corporate or Person Name')], max_length=30, null=True),
        ),
    ]
