# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20161018_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.AddField(
            model_name='table',
            name='topic',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='information_type',
            field=models.CharField(blank=True, choices=[(None, 'No category'), ('full_name', 'Full Name'), ('last_name', 'Last Name'), ('first name', 'First Name'), ('middle_name', 'Middle Name'), ('other_name', 'Other Name'), ('full_add', 'Full Address'), ('street_add', 'Street'), ('city_add', 'City'), ('county_add', 'County'), ('state_add', 'State'), ('zip_add', 'ZIP'), ('other_add', 'Other Address'), ('organization_name', 'Organization Name'), ('corp_or_person_name', 'Corporate or Person Name')], max_length=30, null=True),
        ),
    ]
