# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20161024_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='url',
            field=models.URLField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=300),
            preserve_default=False,
        ),
    ]
