# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20161206_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='url',
        ),
        migrations.AddField(
            model_name='table',
            name='path',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
