# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-15 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20161214_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='database',
        ),
    ]
